### PR TITLE
Add OpenBSD support

### PR DESCRIPTION
**Pull request by adamsteen**
the setup script should set everything up except the git credentials.

I have tested this on my setup with fresh vms, all works great here.

### CODE REVIEW

**Comment by mato** [comment]
Thanks! I had intended to look into this tonight, but due to the current state of `6.4-current` I can't even install basic dependencies needed to build Solo5:

````
12-00-00-38-ea-56$ doas pkg_add git
quirks-3.7 signed on 2018-09-12T09:20:48Z
Can't install gettext-0.19.8.1p1 because of libraries
|library c++.1.0 not found
| /usr/lib/libc++.so.2.0 (system): bad major
Direct dependencies for gettext-0.19.8.1p1 resolve to libiconv-1.14p3
Full dependency tree is libiconv-1.14p3
Can't install git-2.18.0p0: can't resolve gettext-0.19.8.1p1
````

So, adding OpenBSD CI will have to wait a bit longer.

**Comment by adamsteen** [comment]
~~awwww snap (pun intended)~~

~~I take it you have reinstalled or upgraded to the latest snapshot? you will need to otherwise, If so you~~ ~~will need to run pkg_add with [-D snap](http://man.openbsd.org/pkg_add#D)~~

~~OpenBSD are preparing to release 6.4 so i expect thats your problem. misc@ gets that question every 6 months.~~

**Comment by adamsteen** [comment]
@mato I did an upgrade this morning and updated all my packages, with no problems.

Could you please upgrade your system, [boot from bsd.rd](https://www.openbsd.org/faq/faq4.html#bsd.rd) and follow the upgrade prompts and you should be all good. I will try and be on irc later.

**Comment by mato** [comment]
Ah, I went looking for something like `-D snap`, but it was late. That fixes it, thanks. I'm now facing some issues with interaction between nested KVM and OpenBSD `vmm`, so will need to investigate those.

**Comment by adamsteen** [comment]
you might also want to set you timcouter to tsc, ie sysctl kern.timecounter.hardware=tsc, otherwise your time will drift out of control, will tweak the script soon.

see 
https://man.openbsd.org/sysctl.8
https://man.openbsd.org/sysctl.conf.5

**Comment by adamsteen** [comment]
@mato re: my previous comment about setting the time counter.

Could you please let me know if your clock drifts dramatically? if so, you will definitely need to switch to using tsc as the timecounter hardware, its basically required on vmm(4). If so i will check in my updated script.

**Comment by adamsteen** [comment]
@mato have you had a chance to come back and look at this?

**Comment by mato** [comment]
Unfortunately not, I've been busy with the "spt" target for Solo5. Will try to find time to come back to this once I'm back from vacation

**Comment by mato** [comment]
Done in ff50dcd, much easier now with 6.4 and surf 2.0.0. Thanks for the investigation.

**Pull request closed without merging**
